[package]
name = "blogthing"
version = "0.1.0"
edition = "2024"

[dependencies]
axum = "0.8.4"
clap = { version = "4.5.20", features = ["derive"] }
filetime = "0.2.25"
maud = "0.27.0"
tokio = { version = "1.45.1", features = ["full"] }
